apiVersion: v1
kind: ServiceAccount
metadata:
  name: secret-access-sa
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: adminaccess-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: secret-access-sa
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
