apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  name: container-registry-key-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
