apiVersion: apps/v1
kind: Deployment
metadata:
  name: datarouter
spec:
  replicas: 0
  selector:
    matchLabels:
      app: datarouter
  template:
    metadata:
      name: datarouter
      labels:
        app: datarouter
        tier: middle-tier
        container_name: datarouter
        environment: {{ .Values.label.ENVIRONMENT }}
    spec:
      serviceAccountName: common-service-account
      volumes:      
      - name: datarouter
        persistentVolumeClaim:
          claimName: datarouter-pvc
      - name: fluentd-config
        configMap:
          name: datarouter-fluentd-config
      containers:
      - name: datarouter
        image: {{required "Data Router Image Info is mandatory! Read the Project Documentation to understand what and where to configure." .Values.image.DATAROUTER }}
        env:
        - name: DATAROUTER_JAVA_XMX
          valueFrom:
            configMapKeyRef:
              name: resource-config
              key: DATAROUTER_JAVA_XMX
        imagePullPolicy: Always
        {{- with ( pluck .Values.resourceUnit.size .Values.resourceUnit | first ) }}
        resources:
          limits:
            memory: {{ .memory.max.DATAROUTER }}Mi
            cpu: {{ .cpu.max.DATAROUTER }}m
          requests:
            memory: {{ .memory.max.DATAROUTER }}Mi
            cpu: {{ .cpu.max.DATAROUTER }}m
        {{- end }}
        volumeMounts:
        - mountPath: /opt/metricstream/SYSTEMi/datarouter/datarouter.properties
          name: datarouter
          subPath: datarouter.properties
        - mountPath: /opt/metricstream/SYSTEMi/datarouter/log4j.properties
          name: datarouter
          subPath: log4j.properties
        - mountPath: /opt/metricstream/SYSTEMi/datarouter/smc_instrumentation.json
          name: datarouter
          subPath: smc_instrumentation.json
        - mountPath: /opt/metricstream/SYSTEMi/datarouter/logs
          name: datarouter
          subPath: logs
        securityContext:
          readOnlyRootFilesystem: true
      - name: fluentd
        image: {{ .Values.image.LOGZIO }}
        env:
        - name:  LOGZIO_TOKEN
          valueFrom:
            secretKeyRef:
              name: logzio-token-secret
              key: logzio-url
        - name:  LOGZIO_URL
          valueFrom:
            secretKeyRef:
              name: logzio-token-secret
              key: logzio-token
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: POD_SERVICE_ACCOUNT_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.serviceAccountName
        - name: POD_UNIQUE_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        - name: CONTAINER_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['container_name']
        - name: ENVIRONMENT
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['environment']
        - name: APP_TIER
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['tier']
        resources:
          limits:
            cpu: {{ .Values.logzio.cpu }}m
            memory: {{ .Values.logzio.memory }}Mi
          requests:
            cpu: {{ .Values.logzio.cpu }}m
            memory: {{ .Values.logzio.memory }}Mi
        volumeMounts:
        - name: fluentd-config
          mountPath: /fluentd/etc/fluent.conf
          subPath: fluent.conf
        - name: datarouter
          mountPath: /metricstream/SYSTEMi/datarouter/logs
          subPath: logs
      imagePullSecrets:
      - name: container-registry-key
      securityContext:
        runAsUser: 1000
        runAsNonRoot: true
        fsGroup: 1000
      allowedCapabilities: null

