apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
spec:
  ports:
    - name: elasticsearch
      protocol: TCP
      port: 9300
      targetPort: 9300
  selector:
    app: elasticsearch
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
spec:
  replicas: 0
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      name: elasticsearch
      labels:
        app: elasticsearch
        tier: persitent-tier
        container_name: elasticsearch
        environment: {{ .Values.label.ENVIRONMENT }}        
    spec:
      serviceAccountName: common-service-account
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: elasticsearch-pvc
      - name: fluentd-config
        configMap:
          name: elasticsearch-fluentd-config
      containers:
      - name: elasticsearch
        image: {{required "Image Info is mandatory! Read the Project Documentation to understand what and where to configure." .Values.image.ELASTICSEARCH }}
        imagePullPolicy: IfNotPresent
        env:
        - name: ES_JAVA_OPTS
          {{- if (eq "Small" .Values.resourceUnit.size) }}
          value: -Xms512m -Xmx{{ .Values.resourceUnit.small.memory.max.ELASTICSEARCH }}m
          {{- else if (eq "Medium" .Values.resourceUnit.size) }}
          value: -Xms512m -Xmx{{ .Values.resourceUnit.medium.memory.max.ELASTICSEARCH }}m
          {{- else if (eq "Large" .Values.resourceUnit.size) }}
          value: -Xms512m -Xmx{{ .Values.resourceUnit.large.memory.max.ELASTICSEARCH }}m
          {{- else if (eq "Xlarge" .Values.resourceUnit.size) }}
          value: -Xms512m -Xmx{{ .Values.resourceUnit.xlarge.memory.max.ELASTICSEARCH }}m
          {{- end }}
        - name: processors
          value: "1"
        {{- with ( pluck .Values.resourceUnit.size .Values.resourceUnit | first ) }}
        resources:
          limits:
            memory: {{ .memory.max.ELASTICSEARCH }}Mi
            cpu: {{ .cpu.max.ELASTICSEARCH }}m
          requests:
            memory: {{ .memory.max.ELASTICSEARCH }}Mi
            cpu: {{ .cpu.max.ELASTICSEARCH }}m
        {{- end }}
        volumeMounts:
        - mountPath: /data/elasticsearch
          name: data
          subPath: elasticsearch
        - mountPath: /usr/share/elasticsearch/data
          name: data
          subPath: data
        - mountPath: /usr/share/elasticsearch/config/logging.yml
          name: data
          subPath: conf/logging.yml
        - mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
          name: data
          subPath: conf/elasticsearch.yml
        - mountPath: /usr/share/elasticsearch/logs
          name: data
          subPath: logs
        - mountPath: /tmp
          name: data
          subPath: tmp
        securityContext:
          readOnlyRootFilesystem: true
        ports:
        - name: elasticsearch
          containerPort: 9300
      - name: fluentd
        image: {{ .Values.image.LOGGER }}
        env:
        - name:  LOGGER_TOKEN
          valueFrom:
            secretKeyRef:
              name: logger-token-secret
              key: logger-url
        - name:  LOGGER_URL
          valueFrom:
            secretKeyRef:
              name: logger-token-secret
              key: logger-token
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: POD_SERVICE_ACCOUNT_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.serviceAccountName
        - name: POD_UNIQUE_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        - name: CONTAINER_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['container_name']
        - name: ENVIRONMENT
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['environment']
        - name: APP_TIER
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['tier']
        resources:
          limits:
            cpu: {{ .Values.logzio.cpu }}m
            memory: {{ .Values.logzio.memory }}Mi
          requests:
            cpu: {{ .Values.logzio.cpu }}m
            memory: {{ .Values.logzio.memory }}Mi
        volumeMounts:
        - name: fluentd-config
          mountPath: /fluentd/etc/fluent.conf
          subPath: fluent.conf
        - name: data
          mountPath: /usr/share/elasticsearch/logs
          subPath: logs
      imagePullSecrets:
      - name: container-registry-key
      securityContext:
        runAsUser: 1000
        runAsNonRoot: true
        fsGroup: 1000
      allowedCapabilities: null

