apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      name: logstash
      labels:
        app: logstash
        container_name: logstash
    spec:
      containers:
      - name: logstash-container
        image: {{required "Image Info is mandatory! Read the Project Documentation to understand what and where to configure." .Values.image.LOGSTASH }}
        imagePullPolicy: IfNotPresent
      imagePullSecrets:
      - name: container-registry-key-secret

