apiVersion: v1
kind: Service
metadata:
  name: oracle-service
spec:
  ports:
    - name: oracle-service-port
      protocol: TCP
      port: 1521
      targetPort: 1521
  selector:
    app: oracle
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oracle-deployment
spec:
  replicas: 0
  selector:
    matchLabels:
      app: oracle
  template:
    metadata:
      name: oracle
      labels:
        app: oracle
        tier: persistent-tier
        container_name: oracle
        environment: {{ .Values.label.ENVIRONMENT }}
    spec:
      serviceAccountName: common-service-account
      volumes: 
      - name: oracle-data-volume
        persistentVolumeClaim:
          claimName: oracle-persistent-volume-claim
      - name: oracle-dshm-volume
        emptyDir:
          medium: Memory
          sizeLimit: "4096Mi"
      - name: oracle-fluentd-config-volume
        configMap:
          name: oracle-fluentd-configmap
      containers:
      - name: oracle-container
        image: {{required "Image Info is mandatory! Read the Project Documentation to understand what and where to configure." .Values.image.ORACLE }}
        imagePullPolicy: IfNotPresent
        env:
        - name: ORACLE_MAX_MEM
          valueFrom:
            configMapKeyRef:
              name: resource-unit-configmap
              key: ORACLE_MAX_MEM
        ports:
        - name: oracle-port
          containerPort: 1521
        {{- with ( pluck .Values.resourceUnit.size .Values.resourceUnit | first ) }}
        resources:
          limits:
            memory: {{ .memory.max.ORACLE }}Mi
            cpu: {{ .cpu.max.ORACLE }}m
          requests:
            memory: {{ .memory.max.ORACLE }}Mi
            cpu: {{ .cpu.max.ORACLE }}m
        {{- end }}
        volumeMounts:
        - mountPath: /data/oracle/oradata
          name: oracle-data-volume
          subPath: oradata
        - mountPath: /dev/shm
          name: oracle-dshm-volume
        - mountPath: /opt/oracle/product/12.2.0.1/dbhome_1/network/admin
          name: oracle-data-volume
          subPath: opt_oracle/product/12.2.0.1/dbhome_1/network/admin
        - mountPath: /opt/oracle/admin/orcl/adump
          name: oracle-data-volume
          subPath: opt_oracle/admin/orcl/adump
        - mountPath: /opt/oracle/product/12.2.0.1/dbhome_1/dbs
          name: oracle-data-volume
          subPath: opt_oracle/product/12.2.0.1/dbhome_1/dbs
        - mountPath: /opt/oracle/diag/rdbms/orcl
          name: oracle-data-volume
          subPath: opt_oracle/diag/rdbms/orcl
        - mountPath: /opt/oracle/product/12.2.0.1/dbhome_1/rdbms/log
          name: oracle-data-volume
          subPath: opt_oracle/product/12.2.0.1/dbhome_1/rdbms/log
        - mountPath: /tmp
          name: oracle-data-volume
          subPath: tmp
        - mountPath: /var/tmp
          name: oracle-data-volume
          subPath: var_tmp
        securityContext:
          runAsUser: 54321
          readOnlyRootFilesystem: true
      initContainers:
      - name: ri-data-init
        image: {{required "Image Info is mandatory! Read the Project Documentation to understand what and where to configure." .Values.image.RI_DATA_INIT }} 
        args: ["MI_VERSION", {{ .Chart.Version }}]
      - name: fluentd-container
        image: {{ .Values.image.LOGZIO }}
        env:
        - name:  LOGZIO_TOKEN
          valueFrom:
            secretKeyRef:
              name: logzio-token-secret
              key: logzio-token
        - name:  LOGZIO_URL
          valueFrom:
            secretKeyRef:
              name: logzio-token-secret
              key: logzio-url
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: POD_SERVICE_ACCOUNT_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.serviceAccountName
        - name: POD_UNIQUE_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        - name: CONTAINER_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['container_name']
        - name: ENVIRONMENT
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['environment']
        - name: APP_TIER
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['tier']
        resources:
          limits:
            cpu: {{ .Values.logzio.cpu }}m
            memory: {{ .Values.logzio.memory }}Mi
          requests:
            cpu: {{ .Values.logzio.cpu }}m
            memory: {{ .Values.logzio.memory }}Mi
        volumeMounts:
        - name: oracle-fluentd-config-volume
          mountPath: /fluentd/etc/fluent.conf
          subPath: fluent.conf
        - name: oracle-data-volume
          mountPath: /opt/oracle/diag/rdbms/orcl
          subPath: orcl
        securityContext:
          runAsUser: 1000
      imagePullSecrets:
      - name: container-registry-key-secret
      securityContext:
        runAsNonRoot: true
        fsGroup: 54321
      allowedCapabilities: null
