apiVersion: v1
kind: Service
metadata:
  name: tomcat
spec:
  ports:
    - name: tomcat
      protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: tomcat
  {{- if (eq "GKE" .Values.cloudService.provider) }}
  type: NodePort
  {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: tomcat-jmx
spec:
  ports:
    - name: jmx
      protocol: TCP
      port: 8888
      targetPort: 8888
  selector:
    app: tomcat
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat  
spec:
  replicas: 0
  selector:
    matchLabels:
      app: tomcat
  template:
    metadata:
      name: tomcat
      labels:
        app: tomcat
        tier: frontend
        container_name: tomcat
        environment: {{ .Values.label.ENVIRONMENT }}
    spec:
      serviceAccountName: common-service-account
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: tomcat-pvc
      - name: keys
        secret:
          secretName: ms-license-key
      - name: fluentd-config
        configMap:
          name: tomcat-fluentd-config
      containers:
      - name: tomcat
        image: {{required "Image Info is mandatory! Read the Project Documentation to understand what and where to configure." .Values.image.TOMCAT }}
        imagePullPolicy: IfNotPresent
        env:
        - name: POD_NAME
          value: tomcat
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CLASSPATH
          value: "/tomcat/bin/bootstrap.jar:/tomcat/bin/tomcat-juli.jar:/tomcat/extralib/*"
        args:
        - java
        - -server
        - -Xms1024m
        {{- if (eq "Small" .Values.resourceUnit.size) }}
        - -Xmx{{.Values.resourceUnit.small.memory.max.TOMCAT}}m
        {{- else if (eq "Medium" .Values.resourceUnit.size)}}
        - -Xmx{{.Values.resourceUnit.medium.memory.max.TOMCAT}}m
        {{- else if (eq "Large" .Values.resourceUnit.size) }}
        - -Xmx{{.Values.resourceUnit.large.memory.max.TOMCAT}}m
        {{- else if (eq "Xlarge" .Values.resourceUnit.size) }}
        - -Xmx{{.Values.resourceUnit.xlarge.memory.max.TOMCAT}}m
        {{- end }}
        - -Dcatalina.home=/tomcat
        - -Dcatalina.base=/tomcat
        - -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
        - -Djava.util.logging.config.file=/tomcat/conf/logging.properties
        - -Djava.protocol.handler.pkgs=org.apache.catalina.webresources
        - -Djava.io.tmpdir=/tmp
        - -Djava.awt.headless=true
        - -Dlogback.configurationFile=/opt/MetricStream/SYSTEMi/Systemi/Config/logback.xml
        - -Djava.awt.fonts=/opt/java/jre/lib/fonts
        - -Djava.security.policy=/opt/MetricStream/SYSTEMi/Systemi/Config/ecp-app.policy
        - -Djava.library.path=/opt/MetricStream/SYSTEMi/Systemi/webapp/WEB-INF/lib
        - -DMETRICSTREAM.CONFIG=/opt/MetricStream/SYSTEMi/Systemi/Config/config.client.xml
        - -DMETRICSTREAM.HOME=/opt/MetricStream/SYSTEMi/Systemi
        - -DMETRICSTREAM.PROPERTY.NODE_ID=1
        - -Duser.country=US
        - -Duser.language=en
        - -Dcom.sun.management.jmxremote
        - -Dcom.sun.management.jmxremote.authenticate=false
        - -Dcom.sun.management.jmxremote.ssl=false
        - -Dcom.sun.management.jmxremote.port=8888
        - -Dfile.encoding=UTF-8
        - org.apache.catalina.startup.Bootstrap
        - start
        ports:
        - name: tomcat
          containerPort: 8080
        - name: jmx
          containerPort: 8888
        {{- with ( pluck .Values.resourceUnit.size .Values.resourceUnit | first ) }}
        resources:
          limits:
            memory: {{ .memory.max.TOMCAT }}Mi
            cpu: {{ .cpu.max.TOMCAT }}m
          requests:
            memory: {{ .memory.max.TOMCAT }}Mi
            cpu: {{ .cpu.max.TOMCAT }}m
        {{- end }}
        volumeMounts:
        - mountPath: /opt/MetricStream/SYSTEMi
          subPath: SYSTEMi
          name: data
        - mountPath: /opt/MetricStream/SYSTEMi/Systemi/log
          subPath: client_log
          name: data
        - mountPath: /opt/MetricStream/SYSTEMi/Systemi/keys
          name: keys
        - mountPath: /tomcat/conf
          name: data
          subPath: conf
        - mountPath: /tomcat/logs
          name: data
          subPath: logs
        - mountPath: /tomcat/work
          name: data
          subPath: work
        - mountPath: /tmp
          name: data
          subPath: tomcat_tmp
        securityContext:
          readOnlyRootFilesystem: true
      - name: libreoffice
        image: {{required "Image Info is mandatory! Read the Project Documentation to understand what and where to configure." .Values.image.LIBREOFFICE }}
        imagePullPolicy: IfNotPresent
        {{- with ( pluck .Values.resourceUnit.size .Values.resourceUnit | first ) }}
        resources:
          limits:
            memory: {{ .memory.max.LIBREOFFICE }}Mi
            cpu: {{ .cpu.max.LIBREOFFICE }}m
          requests:
            memory: {{ .memory.max.LIBREOFFICE }}Mi
            cpu: {{ .cpu.max.LIBREOFFICE }}m
        {{- end }}
        ports:
        - name: libreoffice
          containerPort: 8997
        volumeMounts:
        - mountPath: /opt/MetricStream/SYSTEMi
          subPath: SYSTEMi
          name: data
        - mountPath: /home/kairos
          subPath: libre_kairos
          name: data
        - mountPath: /tmp
          subPath: libre_tmp
          name: data
        - mountPath: /var/tmp
          subPath: libre_var_tmp
          name: data
        securityContext:
          readOnlyRootFilesystem: true
      - name: fluentd
        image: {{ .Values.image.LOGZIO }}
        env:
        - name:  LOGZIO_TOKEN
          valueFrom:
            secretKeyRef:
              name: logzio-token-secret
              key: logzio-url
        - name:  LOGZIO_URL
          valueFrom:
            secretKeyRef:
              name: logzio-token-secret
              key: logzio-token
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: POD_SERVICE_ACCOUNT_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.serviceAccountName
        - name: POD_UNIQUE_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        - name: CONTAINER_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['container_name']
        - name: ENVIRONMENT
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['environment']
        - name: APP_TIER
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['tier']
        resources:
          limits:
            cpu: {{ .Values.logzio.cpu }}m
            memory: {{ .Values.logzio.memory }}Mi
          requests:
            cpu: {{ .Values.logzio.cpu }}m
            memory: {{ .Values.logzio.memory }}Mi
        volumeMounts:
        - name: fluentd-config
          mountPath: /fluentd/etc/fluent.conf
          subPath: fluent.conf
        - name: data
          mountPath: /tomcat/logs
          subPath: logs
        - name: data
          mountPath: /opt/MetricStream/SYSTEMi/Systemi/log
          subPath: client_log
      imagePullSecrets:
      - name: container-registry-key
      securityContext:
        runAsUser: 1000
        runAsNonRoot: true
        fsGroup: 1000
      allowedCapabilities: null
