kind: ConfigMap
apiVersion: v1
metadata:
  name: mongodb-fluentd-configmap
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
data:
  fluent.conf: |-
    {{ .Files.Get "config/fluentd/mongodb.conf" | nindent 4 }}
