kind: ConfigMap
apiVersion: v1
metadata:
  name: activemq-config
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
data:
  activemq.xml: |-
    {{ .Files.Get "config/activemq/activemq.xml" | nindent 4 }}
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: activemq-log4j
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
data:
  log4j.properties: |-
    {{ .Files.Get "config/activemq/log4j.properties" | nindent 4 }}
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: activemq-jetty
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
data:
  jetty.xml: |-
    {{ .Files.Get "config/activemq/jetty.xml" | nindent 4 }}
