apiVersion: apps/v1
kind: Deployment
metadata:
  name: oracle-deployment
spec:
  replicas: 0
  selector:
    matchLabels:
      app: oracle
  template:
    metadata:
      name: oracle
      labels:
        app: oracle
        tier: persistent-tier
        container_name: oracle
        environment: {{ .Values.label.ENVIRONMENT }}
    spec:
      serviceAccountName: common-service-account
      volumes: 
      - name: oracle-data-volume
        persistentVolumeClaim:
          claimName: oracle-persistent-volume-claim
      containers:
      - name: oracle-container
        image: {{required "Image Info is mandatory! Read the Project Documentation to understand what and where to configure." .Values.image.RI_DATA_INIT_BACKUP }}
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /data/oracle/oradata
          name: oracle-data-volume
          subPath: oradata
        env: 
        - name: AWS_DEFAULT_REGION
          value: {{ .Values.aws.region }}
        - name: AWS_ACCESS_KEY_ID
          value: {{ .Values.aws.access.key }}
        - name: AWS_SECRET_ACCESS_KEY
          value: {{ .Values.aws.secret.access.key }}
      imagePullSecrets:
      - name: container-registry-key-secret
