apiVersion: batch/v1
kind: Job
metadata:
  name: instance-restore
spec:
  template:
    metadata:
      name: instance-restore
    spec:
      serviceAccountName: secret-access-sa
      volumes:
      - name: tomcat
        persistentVolumeClaim:
          claimName: tomcat-persistent-volume-claim
      - name: oracle
        persistentVolumeClaim:
          claimName: oracle-persistent-volume-claim
      containers:
      - name: instance-restore
        image: {{ required "Image Info is mandatory! Read the Project Documentation to understand what and where to configure." .Values.image.INSTANCE_RESTORE_UPGRADE }}
        imagePullPolicy: IfNotPresent
        args:
        - {{ .Release.Namespace }}
        - k8s.metricstream.com
        volumeMounts:
        - mountPath: /opt/metricstream/SYSTEMi
          subPath: SYSTEMi
          name: tomcat
        - mountPath: /oracle
          name: oracle
          subPath: oradata
      restartPolicy: Never
      imagePullSecrets:
      - name: container-registry-key-secret
