apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: activemq
spec:
  podSelector:
    matchLabels:
      app: activemq
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: tomcat
    ports:
    - protocol: TCP
      port: 61616
  egress: []