apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: datarouter
spec:
  podSelector:
    matchLabels:
      app: datarouter
  policyTypes:
  - Ingress
  - Egress
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: tomcat
  - to:
    - podSelector:
        matchLabels:
          app: elasticsearch
    ports:
    - protocol: TCP
      port: 9300
  - to:
    - namespaceSelector:
        matchLabels:
          name: kube-system
    ports:
    - protocol: UDP
      port: 53
  ingress:
  - {}