apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  name: ms-license-key
data:
  MetricStream_key.pub: |-
    {{ .Files.Get "config/license-keys/metricstream-key.pub" }}
  MetricStream_license.xml: |-
    {{ .Files.Get "config/license-keys/metricstream-license.xml" }}
