label:
  ENVIRONMENT: development
image:
  TOMCAT: metricstreaminc/ri-app:7.19.6
  DATAROUTER: metricstreaminc/datarouter:2.17.7-jre8u212-b04
  ACTIVEMQ: metricstreaminc/activemq:5.14.5-jre8u212-b04
  ELASTICSEARCH: metricstreaminc/elasticsearch:2.4.1-jre8u212-b04-m7.3.3
  MONGO: metricstreaminc/mongodb:4.1.10
  ORACLE: metricstreaminc/oracle:12.2.0.1-ee
  LOGSTASH: metricstreaminc/logstash:7.0.0-ojdbc6
  LOGZIO: metricstreaminc/fluent:1.4.2-1.0-es-3.4.3
  RI_DATA_INIT: metricstreaminc/ri-data-init:1.0.0
  LIVE_CHECK: metricstreaminc/live-check:1.0.0
  KIBANA: docker.elastic.co/kibana/kibana-oss:6.3.2
  ELASTICSEARCH_LOGGING: k8s.gcr.io/elasticsearch:v6.3.0
logzio:
  cpu: 100
  memory: 400
resourceUnit:
  small:
    storage:
      size:
        ACTIVEMQ: 6
        ELASTICSEARCH: 6
        MONGO: 6
        ORACLE: 50
        TOMCAT: 12
    memory:
      max:
        ORACLE: 9216
        TOMCAT: 4096
        ACTIVEMQ: 1024
        ELASTICSEARCH: 2048
        MONGO: 2048
        DATAROUTER: 1024
        LIBREOFFICE: 1024
    cpu:
      max:
        ORACLE: 15000
        TOMCAT: 4000
        ACTIVEMQ: 250
        ELASTICSEARCH: 500
        MONGO: 250
        DATAROUTER: 250
        LIBREOFFICE: 250
  medium: 
    storage:
      size:
        ACTIVEMQ: 50
        ELASTICSEARCH: 100
        MONGO: 55
        ORACLE: 400
        TOMCAT: 400
    memory:
      max:
        ORACLE: 12288
        TOMCAT: 8192
        ACTIVEMQ: 2048
        ELASTICSEARCH: 4096
        MONGO: 2048
        DATAROUTER: 2048
        LIBREOFFICE: 2048
    cpu:
      max:
        ORACLE: 3000
        TOMCAT: 2000
        ACTIVEMQ: 500
        ELASTICSEARCH: 1000
        MONGO: 500
        DATAROUTER: 500
        LIBREOFFICE: 500
  large:
    storage:
      size:
        ACTIVEMQ: 100
        ELASTICSEARCH: 300
        MONGO: 95
        ORACLE: 750
        TOMCAT: 750
    memory:
      max:
        ORACLE: 24576
        TOMCAT: 18432
        ACTIVEMQ: 4096
        ELASTICSEARCH: 8192
        MONGO: 4096
        DATAROUTER: 4096
        LIBREOFFICE: 2048
    cpu:
      max:
        ORACLE: 6000
        TOMCAT: 4000
        ACTIVEMQ: 1000
        ELASTICSEARCH: 2000
        MONGO: 1000
        DATAROUTER: 1000
        LIBREOFFICE: 1000
  xlarge:
    storage:
      size:
        ACTIVEMQ: 100
        ELASTICSEARCH: 500
        MONGO: 395
        ORACLE: 1500
        TOMCAT: 1500
    memory:
      max:
        ORACLE: 49152
        TOMCAT: 36864
        ACTIVEMQ: 8192
        ELASTICSEARCH: 16384
        MONGO: 8192
        DATAROUTER: 8192
        LIBREOFFICE: 4096
    cpu:
      max:
        ORACLE: 12000
        TOMCAT: 8000
        ACTIVEMQ: 2000
        ELASTICSEARCH: 4000
        MONGO: 2000
        DATAROUTER: 2000
        LIBREOFFICE: 2000
