apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: activemq-persistent-volume-claim
  annotations:
    volume.beta.kubernetes.io/storage-class: gp2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    {{- with ( pluck .Values.resourceUnit.size .Values.resourceUnit | first ) }}
    requests:
      storage: {{ .storage.size.ACTIVEMQ }}Gi
    {{- end }}
