apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datarouter-persistent-volume-claim
  annotations:
    volume.beta.kubernetes.io/storage-class: ms-storage-class
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
