apiVersion: v1
kind: Service
metadata:
  name: maintenance
  labels:
    app: maintenance
    tier: app
    role: master
spec:
  ports:
    - name: ssh
      protocol: TCP
      port: 22
      targetPort: 22
  type: NodePort
  selector:
    app: maintenance
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: maintenance-deployment
spec:
  replicas: 0
  template:
    metadata:
      name: maintenance-pod
      labels:
        app: maintenance
        tier: app
        role: master
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - tomcat
            topologyKey: kubernetes.io/hostname
      volumes:
      - name: tomcatdata
        persistentVolumeClaim:
          claimName: tomcat-data
      containers:
      - name: maintenance
        image: {{required "Image Info is mandatory! Read the Project Documentation to understand what and where to configure." .Values.image.MAINTENANCE }}
        imagePullPolicy: IfNotPresent
        ports:
        - name: maintenance-ssh
          containerPort: 22
        volumeMounts:
        - mountPath: /home/metricstream
          name: tomcatdata
      restartPolicy: Always
      imagePullSecrets:
      - name: container-registry-key
