apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  name: metricstream-license-keys-secret
data:
  MetricStream_key.pub: |-
    {{ .Files.Get "config/license-keys/metricstream-key.pub" | b64enc }}
  MetricStream_license.xml: |-
    {{ .Files.Get "config/license-keys/metricstream-license.xml" | b64enc }}
